### ISSUE TITLE
Click the X on the Import Existing Configuration dialog cause HueForge to close and reopen itself

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#124]
**Bug Severity:** 2

**Description:**
Click the X on the Import Existing Configuration dialog cause HueForge to close and reopen itself

**Reproduction Steps:**
1.) Launch HueForge version v0.8.0-Beta-2-Test
2.) Click File -> Import Existing Configuration
3.) Click the X on the Dialog
4.) Observe HueForge

**Result:**
HueForge Closes and reopens itself.

**Expected Result:**
Import Existing Configuration dialog closes.

**Comment by slavedas** [comment]
Fixed

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.8.0-beta-2-10-g8c267e9. Closing bug as fixed.
