### ISSUE TITLE
Clicking the Copy Selected HueForge Configs option within the Import Existing Configuration dialog causes nothing to occur

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#125]
**Bug Severity:** 2

**Description:**
Clicking the Copy Selected HueForge Configs option within the Import Existing Configuration dialog causes nothing to occur

**Reproduction Steps:**
1.) Launch HueForge version v0.8.0-Beta-2-Test
2.) Click File -> Import Existing Configuration
3.) Click the Copy Selected HueForge Configs button
4.) Observe HueForge

**Result:**
Nothing occurs.
![image](https://github.com/user-attachments/assets/efe2c8a1-23d9-41ee-a105-c6434432efed)

**Expected Result:**
HueForge closes and imports the Existing Configuration selected from the selected Possible HueForge Folders drop down.

**Comment by slavedas** [comment]
This should be fixed on the new update as well.

**Comment by MajorGamerGeek** [comment]
Cannot verify in the latest HueForge build on windows because of issue https://github.com/HueForge-Official/HueForge/issues/137

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.8.1-rc1 on Windows. Closing bug as fixed.
