### ISSUE TITLE
Import Existing Configuration dialog is titled HueForge

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#127]
**Bug Severity:** 3

**Description:**
Import Existing Configuration dialog is titled HueForge

**Reproduction Steps:**
1.) Launch HueForge version v0.8.0-Beta-2-Test
2.) Click File -> Import Existing Configuration
3.) Observe Import Existing Configuration dialog

**Result:**
Import Existing Configuration dialog is titled HueForge
![image](https://github.com/user-attachments/assets/d48fbacc-7803-4d00-bfd7-6cd7d1387b4c)

**Expected Result:**
Import Existing Configuration dialog is titled "Import Existing Configuration - HueForge"

**Comment by slavedas** [comment]
This should be fixed (though I have it as "HueForge - Importing Existing Configuration" in the new update

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.8.0-beta-2-10-g8c267e9. Closing bug as fixed.
