### ISSUE TITLE
The Import Existing Configuration windows does not open when selected from the File Menu

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#137]
**Bug Severity:** 2

**Description:**
The Import Existing Configuration window does not open when selected from the File Menu

**Reproduction Steps:**
1.) Launch HueForge version v0.8.0-Test-1 on Windows
2.) Click File -> Import Existing Configuration
3.) Observe HueForge

**Result:**
Users is prompted with two Duplicate File Found dialog
![image](https://github.com/user-attachments/assets/a8022a42-a0c3-4fc8-a656-c7c5826fb3d3)

**Expected Result:**
The Existing Configuration window displays with options on which configuration to import.

**Comment by slavedas** [comment]
This was on a brand new system?  No previous HueForge?

**Comment by slavedas** [comment]
Found the two bugs.  A conditional statement got deleted somewhere.

**Comment by MajorGamerGeek** [comment]
> This was on a brand new system? No previous HueForge?
> [](#)

This was not a brand new system.

**Comment by slavedas** [comment]
Yeah I figured out this error.  I had accidentally deleted a conditional so
it was ALWAYS running.

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.8.1-rc1. Closing bug as fixed.
