### ISSUE TITLE
Rectangular STL's loads to the right cutoff in the model preview window and the "Drop Image Here" text

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#22]
**Description:** Rectangular STL's loads to the right cutoff in the model preview window and the "Drop Image Here" text

**Repro Steps:**

1. Launch HueForge v0.6.2
2. Click File -> File Open -> STL and select a rectangular STL file and Click Open
3. Observe the model preview window

**Result:**
Rectangular STL's loads to the right cutoff in the model preview window and the "Drop Image Here" text
![image](https://github.com/HueForge-Official/HueForge/assets/23288009/5975039e-19cb-4b90-a13f-fc0d3c213401)

**Expected Result:**
STLs should be centered in the model preview window and not cut off in anyway. Clicking Reset View does not fix the issue.

**Comment by slavedas** [comment]
The issue here is that the preview doesn't go away, not that the model
isn't centered in it's window

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge 0.6.4. Closing bug as fixed.
