### ISSUE TITLE
The Lighting Settings Front Lit button text is larger then all other button texts

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#40]
**Bug Severity:** 3

**Description:** The Lighting Settings Front Lit button text is larger then all other button texts

**Reproduction Steps:**
1.) Launch HueForge version v0.7.0-Test 12/07/2023
2.) Observe the Lighting Settings

**Result:**
The Front Lit button text is larger then all other button texts. (See attached Screenshot)

**Expected Result:**
The Front Lit button text should be the same size to the other buttons within the HueForge UI.

![image](https://github.com/HueForge-Official/HueForge/assets/23288009/14ab1b20-5b9c-4769-b322-44271d823b3c)

**Comment by slavedas** [comment]
Fixed.

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in 0.7.0-Test build date 12/09/23. Closing bug as fixed.
