### ISSUE TITLE
No Space between the Filament Color Name and Hex Code text within the These Filaments Are Updated Dialog

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#41]
**Bug Severity:** 3

**Description:** No Space between the Filament Color Name and Hex Code text within the These Filaments Are Updated Dialog

**Reproduction Steps:**
1.) Launch HueForge version v0.7.0-Test 12/07/2023
2.) Click the New Filament button within the Filament Library
3.) Click Ok on the Select Color Dialog
4.) Click Add on the Add Filament Dialog
5.) Click Save button within the Filament Library Dialog
6.) Observe the "These Filaments Are Updated. Would you like to save these changes?" dialog

**Result:**
No Space is displayed between the Filament Color Name and Hex Code text. (See Attached Screenshot)

![image](https://github.com/HueForge-Official/HueForge/assets/23288009/9e68e07b-0a01-4bc3-a4c8-711792023791)

**Expected Result:**
A space should be displayed between the Filament Color Name and Hex Code text

**Comment by slavedas** [comment]
Fixed awaiting new build.

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge build 0.7.0-Test date 12/09/23. Closing bug as fixed.
