### ISSUE TITLE
Blendinig Bars don't update to reflect the change in Front Lit/Back lit status

### ISSUE THREAD

**Issue by slavedas** [HueForge-Official/HueForge#43]
Load an image
Set some slider
Observe the blending bar indicators
Change from Front Lit to Back Lit
Blending bar does not change to match the display.

**Comment by slavedas** [comment]
This should be fixed in the current version

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.7.0-RC1. Closing bug as fixed.
