### ISSUE TITLE
The "Drop Image Here" text is not centered in the preview image area

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#45]
**Bug Severity:** 3

**Description:** The "Drop Image Here" text is not centered in the preview image area

**Reproduction Steps:**
1.) Launch HueForge version v0.7.0-Test 12/09/2023
2.) Observe the UI

**Result:**
The "Drop Image Here" text is not centered in the preview image area. (See Attached Screenshot)

![image](https://github.com/HueForge-Official/HueForge/assets/23288009/b8298232-0dc8-421c-9d64-dfbec24d7f4b)

**Expected Result:**
The "Drop Image Here" text should be centered in the preview image area

**Comment by slavedas** [comment]
This is fixed in the current test version, please confirm (image is centered as well)

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge version v0.7.0-Test 12/20/2023 build. Verified both the "Drop Image Here" text and image you open in HueForge are correctly centered. Closing bug as fixed.
