### ISSUE TITLE
Filaments from a users filament library and filaments from a project are displayed in a different font style within the Filament Library

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#61]
**Bug Severity:** 3

**Description:** 
Filaments from a users filament library and filaments from a project are displayed in a different font style within the Filament Library.

**Reproduction Steps:**
1.) Launch HueForge version v0.7.0-Beta-1
2.) File -> Open File -> Project
3.) Select Color_Pop_Cardinals.hfp and click
4.) Click on the filter edit box and search for Chocolate
5.) Observe the two Chocolate filaments text within the Filament Library

**Result:**
The found filaments are displayed in a different font style.
![image](https://github.com/HueForge-Official/HueForge/assets/23288009/e30f8aa7-c152-4905-bf98-2b32279e44cd)

**Expected Result:**
Filaments from a users filament library and filaments from a project should be displayed in the same font style.

**Comment by MajorGamerGeek** [comment]
Bug still reproduces in HueForge v0.7.0-beta-3 on both macOS and Windows.

**Comment by slavedas** [comment]
I would fix this if I had any idea why it was doing it

**Comment by slavedas** [comment]
It's true for Copy Filament new filaments as well though in my case I'm just seeing it being not bold where the normal font is bold

**Comment by slavedas** [comment]
I take that back.  I believe I have solved it.

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.7.1-Hotfix 03/12/24. Closing bug as fixed.
