### ISSUE TITLE
No window boarder is displayed below the Lighting Settings and General Options and Operations windows on MacOSArm64

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#66]
**Bug Severity:** 3

**Description:** 
No window boarder is displayed below the Lighting Settings and General Options and Operations windows on MacOSArm64.

**Reproduction Steps:**
1.) Launch HueForge version v0.7.0-Beta-2 on macOS Sonoma 14.3
2.) Observe the HueForge UI

**Result:**
No window boarder is displayed below the Lighting Settings and General Options and Operations windows
![image](https://github.com/HueForge-Official/HueForge/assets/23288009/b92bef0b-2511-41c1-bde6-1728ab426b0a)

**Expected Result:**
A window boarder should be displayed below the Lighting Settings and General Options and Operations when docked.

**Comment by slavedas** [comment]
You complained about the empty space!  The only way I could get rid of it
was to set a maximum size an that removes the lower border.

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed on macOS HueForge v0.7.0-Beta-2.2. Closing bug as Fixed.
