### ISSUE TITLE
Color Pop and Color Aware HueForge projects are not loading correctly

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#74]
**Bug Severity:** 1

**Description:** 
Color Pop and Color Aware HueForge projects are not loading correctly

**Reproduction Steps:**
1.) Launch HueForge version v0.7.0 on Windows
2.) Click File -> Open File -> Project
3.) Select the a Color Pop or Color Aware project such as Parrot-Color-Match.hfp and click open
4.) Observe the HueForge UI

**Result:**
The Luminace drop down is blank and other Color Aware controls are not displayed and the HueForge Mesh is rendered incorrectly.

**Expected Result:**
Color Pop and Color Aware project should always open correctly in HueForge

**Comment by slavedas** [comment]
This bug does not exist and that file does not exist
