### ISSUE TITLE
Clicking the Add button within the Add Filament Dialog from the Create Filament option does not add a new Filament

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#79]
**Bug Severity:** 2

**Description:** 
Clicking the Add button within the Add Filament Dialog from the Create Filament option does not add a new Filament.

**Reproduction Steps:**
1.) Launch HueForge version v0.7.1-Hotfix 3/10/24
2.) Click File -> Open File -> Image
3.) Select any image such as Color_Aware_Test.png and Click Open
4.) Right click anywhere on the project image and select Create Filament
5.) Input a Brand and Name
6.) Finally click the Add button to add the new Filament 

**Result:**
Add Filament Dialog says "Enter new Filament Information" and your new filament is not added within your HueForge Filament Library.

**Expected Result:**
The Add button should not be displayed within the Add Filament Dialog.

**Comment by slavedas** [comment]
So same bug but with a different version of the dialog. Okay I can fix
that.

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.7.1-Hotfix 03/11/24. Closing bug as fixed.
