### ISSUE TITLE
Color Pop luminance method projects are being rendered incorrectly in the HueForge mesh preview window

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#87]
**Bug Severity:** 2

**Description:**
Color Pop luminance method projects are being rendered incorrectly in the HueForge mesh preview window

**Reproduction Steps:**
1.) Launch HueForge version v0.7.1-Hotfix 03/16/24 on Windows
2.) Click File -> Open File -> Project
3.) Select any included Color Pop project such as "Blended Relief Cameo Example.hfp" or "Woman in Spacesuit Torso Color Pop.hfp" and click Open
5.) Observe the HueForge UI

**Result:**
The loaded color pop project is rendered incorrectly in mesh window:
![image](https://github.com/HueForge-Official/HueForge/assets/23288009/6103de3f-a2e9-4686-9ee0-5ac11950d017)
![image](https://github.com/HueForge-Official/HueForge/assets/23288009/374ed223-7948-425a-9fbb-c265e3690634)

**Expected Result:**
The File Load dialog should open and the currently open project should stay opened.

**Notes:**
Bug occurs with both Nvidia RTX 3060M and Intel Iris graphics.

**Comment by slavedas** [comment]
I sent you two replacement projects.  Color Pop had multiple rendering issues that I believe I sorted and adjusted the projects for

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in HueForge v0.7.1-Hotfix-03/23/24. Closing bug as fixed.
