### ISSUE TITLE
The Unable to Open File Dialog does not list *.svg as a supported file type

### ISSUE THREAD

**Issue by MajorGamerGeek** [HueForge-Official/HueForge#93]
**Bug Severity:** 3

**Description:**
The Unable to Open File Dialog does not list *.svg as a supported file type.

**Reproduction Steps:**
1.) Launch HueForge version v0.7.1-test-26-g132e83d on Windows
2.) Drag an unsupported file type onto the HueForge UI such as an *.exe
3.) Observe the Unable to Open File dialog

**Result:**
"File must be opened of the following: *.hfp, *.stl, *.jpg, *.jpeg, *.png, *.webp"
![image](https://github.com/HueForge-Official/HueForge/assets/23288009/69293ccb-efe1-4b4c-8889-fece62f84025)

**Expected Result:**
The Unable to Open File Dialog should list *.svg as a supported file type.

**Comment by slavedas** [comment]
Also you can't open SVGs from any menu... good catch

**Comment by MajorGamerGeek** [comment]
Verified bug is fixed in v0.7.1-beta-rc1 on macOS and Windows. Closing bug as fixed.
